id: ABA15B111
title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the Glorious
  Vajrasattva, a Method of Purification and Accomplishment for Both Self and Others'
type: translation
pechas:
- ICA4841D7
- I66C49404
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:26.011909
  last_modified_at: 2023-01-04 12:50:26.011928
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  ICA4841D7/FC4A: E0AF
  I66C49404/46B7: E0AF
